require 'aloha/controllers/app/auth'
require 'aloha/controllers/app/install'
require 'aloha/controllers/app/login'
require 'aloha/controllers/app/logout'
require 'aloha/controllers/app/welcome'
require 'aloha/controllers/app/wizard'
require 'aloha/controllers/app/messages'
